name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npx nx lint

      - name: Run Tests
        run: echo "Skipping tests. No tests defined."

      - name: Docker Login
        uses: docker/login-action@v3
        env:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: npx nx run tomorrow:docker-build --configuration=production

      - name: Push Docker Image
        run: docker push ankemp/tomorrow
